[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
version = "1.0.0"

[tool.semantic_release]
build_command = ""
tag_format = "v{version}"
major_on_zero = true
commit_parser = "conventional"

[tool.semantic_release.branches.main]
match = "^(main|master|act-harness)$"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.branches.dev]
match = ".+"
prerelease = true
prerelease_token = "dev"

[tool.semantic_release.remote]
type = "github"
token = { env = "GH_TOKEN" }
