[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
version = "1.0.0"

[tool.semantic_release]
version_variables = ["pyproject.toml:project.version"]
commit_message = "chore(release): {version} [skip ci]"
build_command = ""
tag_format = "v{version}"
